package view.impl;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import view.interfaces.ICharacterCreationScreenView;

import javax.swing.*;
import java.awt.*;

public class CharacterCreationScreenViewImpl implements ICharacterCreationScreenView {
    private JPanel mainViewPanel;
    private JButton selectColorButton;
    private JTextField nameTextField;
    private JButton finalizeButton;
    private JButton resetButton;
    private JLabel spriteColorLabel;
    private JLabel nameLabel;
    private JLabel spriteEyeColorDisplayLabel;
    private JLabel spriteMainColorDisplayLabel;
    private JButton selectEyeColorButton;


    public JButton getSelectColorButton() {
        return selectColorButton;
    }

    @Override
    public JButton getSelectEyeColorButton() {
        return selectEyeColorButton;
    }

    public JTextField getNameTextField() {
        return nameTextField;
    }

    @Override
    public JPanel getMainDisplayPanel() {
        return this.mainViewPanel;
    }

    @Override
    public Color getSelectedSpriteColor() {
        return spriteMainColorDisplayLabel.getBackground();
    }

    @Override
    public String getEnteredName() {
        return nameTextField.getText();
    }

    @Override
    public Color getSelectedEyeColor() {
        return spriteEyeColorDisplayLabel.getBackground();

    }

    public JButton getFinalizeButton() {
        return finalizeButton;
    }


    public JLabel getSpriteColorLabel() {
        return spriteColorLabel;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public JLabel getSpriteEyeColorDisplayLabel() {
        return spriteEyeColorDisplayLabel;
    }

    @Override
    public JButton getClearButton() {
        return resetButton;
    }

    @Override
    public JLabel getSpriteMainColorDisplayLabel() {
        return spriteMainColorDisplayLabel;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainViewPanel = new JPanel();
        mainViewPanel.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        nameLabel = new JLabel();
        nameLabel.setText("JavaGachi Name");
        mainViewPanel.add(nameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainViewPanel.add(spacer1, new GridConstraints(0, 3, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        spriteColorLabel = new JLabel();
        spriteColorLabel.setText("Sprite Color");
        mainViewPanel.add(spriteColorLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        spriteMainColorDisplayLabel = new JLabel();
        spriteMainColorDisplayLabel.setText(" ");
        mainViewPanel.add(spriteMainColorDisplayLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(32, 32), new Dimension(32, 32), null, 0, false));
        selectColorButton = new JButton();
        selectColorButton.setText("Select Color");
        mainViewPanel.add(selectColorButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTextField = new JTextField();
        mainViewPanel.add(nameTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        finalizeButton = new JButton();
        finalizeButton.setText("Finalize");
        mainViewPanel.add(finalizeButton, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        resetButton = new JButton();
        resetButton.setText("Reset");
        mainViewPanel.add(resetButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Sprite Eye Color");
        mainViewPanel.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        spriteEyeColorDisplayLabel = new JLabel();
        spriteEyeColorDisplayLabel.setText(" ");
        mainViewPanel.add(spriteEyeColorDisplayLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(32, 32), new Dimension(32, 32), null, 0, false));
        selectEyeColorButton = new JButton();
        selectEyeColorButton.setText("Select Eye Color");
        mainViewPanel.add(selectEyeColorButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainViewPanel;
    }
}
