package view.impl;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import model.impl.JavaGachi;
import view.interfaces.IFriendListScreenView;

import javax.swing.*;
import java.awt.*;

public class FriendListScreenViewImpl implements IFriendListScreenView {
    private JPanel mainViewPanel;
    private JList javaGachiList;
    private JButton showSelectedButton;
    private JLabel javaGachiSpriteDisplayLabel;
    private JLabel JavaGachiNameDisplayLabel;
    private JLabel JavaGachiAgeDisplayLabel;
    private JPanel javaGachiDisplayPanel;

    @Override
    public JList<JavaGachi> getJavaGachiJList() {
        return javaGachiList;
    }

    @Override
    public JLabel getJavaGachiSpriteDisplayLabel() {
        return javaGachiSpriteDisplayLabel;
    }

    @Override
    public JLabel getJavaGachiAgeDisplayLabel() {
        return JavaGachiAgeDisplayLabel;
    }

    @Override
    public JLabel getJavaGachiNameDipslayLabel() {
        return JavaGachiNameDisplayLabel;
    }

    @Override
    public JButton getShowButton() {
        return showSelectedButton;
    }

    @Override
    public JPanel getMainDisplayPanel() {
        return mainViewPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainViewPanel = new JPanel();
        mainViewPanel.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        javaGachiList = new JList();
        mainViewPanel.add(javaGachiList, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        showSelectedButton = new JButton();
        showSelectedButton.setText("Show Selected");
        mainViewPanel.add(showSelectedButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        javaGachiDisplayPanel = new JPanel();
        javaGachiDisplayPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainViewPanel.add(javaGachiDisplayPanel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        javaGachiSpriteDisplayLabel = new JLabel();
        javaGachiSpriteDisplayLabel.setText("");
        javaGachiDisplayPanel.add(javaGachiSpriteDisplayLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        JavaGachiNameDisplayLabel = new JLabel();
        JavaGachiNameDisplayLabel.setText("");
        javaGachiDisplayPanel.add(JavaGachiNameDisplayLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        JavaGachiAgeDisplayLabel = new JLabel();
        JavaGachiAgeDisplayLabel.setText("");
        javaGachiDisplayPanel.add(JavaGachiAgeDisplayLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Name:");
        javaGachiDisplayPanel.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Age (minutes):");
        javaGachiDisplayPanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainViewPanel;
    }
}
